name: Build realtime release
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.py'
  push:
    branches:
      - main
    paths:
      - '**.py'
permissions:
  contents: write
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'false'

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.0'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Generate program
        run: |
          pyinstaller -D --distpath .\dist\ -i .\img\Paimon.ico --contents-directory libraries --uac-admin -n "PaimonAssistant" AutoClick.py -y -w

      - name: Move assets to dist directory
        run: |
          xcopy /E /I /Y .\img\ .\dist\PaimonAssistant\img\
          xcopy /Y .\README.md .\dist\PaimonAssistant\

      - name: Create zip archive
        run: |
          ren .\dist\PaimonAssistant PaimonAssistant${{ github.run_number }}
          powershell Compress-Archive -Path .\dist\PaimonAssistant${{ github.run_number }}\ -DestinationPath .\dist\PaimonAssistant${{ github.run_number }}.zip -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: PaimonAssistant${{ github.run_number }}.zip
          path: ./dist/PaimonAssistant${{ github.run_number }}.zip

